
SENDGRID_PASSWORD: rrlpsr2m
SENDGRID_USERNAME: app26700261@heroku.com
DEVISE_SECRET_KEY: 3b8c13085ddc9969c910542b3da117520b776e1743358f3a4474e46882965f34eebc089d8ac4e31f875f44ee27ae9889a75ff2a6cfdae3f404eebcb5f854ba3

AWS_ACCESS_KEY_ID: AKIAIUROLR3LX64SZD4Q
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: nick-bloccit-development
production:
  AWS_BUCKET: nick-bloccit-production